# Generated by Django 2.1.3 on 2018-11-30 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'verbose_name': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='clipping.Autor', verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Livros',
                'verbose_name': 'Livro',
            },
        ),
        migrations.CreateModel(
            name='Recorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Recorte')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('posicao', models.TextField(blank=True, null=True, verbose_name='Posição/Página')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorte', to='clipping.Autor', verbose_name='Autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorte', to='clipping.Livro', verbose_name='Livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorte', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Recortes',
                'verbose_name': 'Recorte',
            },
        ),
    ]
