# Generated by Django 2.1.3 on 2018-12-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping', '0002_auto_20181201_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.TextField(verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='recorte',
            name='posicao',
            field=models.TextField(blank=True, null=True, verbose_name='Posição/Página'),
        ),
    ]
